services:
  postgres:
    image: postgres
    container_name: litbooks
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: litbooks
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4

    environment:
      - PGADMIN_DEFAULT_EMAIL=root@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root

    ports:
      - 5050:80